
---- This script was generated by the ERD tool in pgAdmin 4.
---- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
--BEGIN;


--CREATE TABLE IF NOT EXISTS public."Customer"
--(
--    "CustID" bigint GENERATED ALWAYS AS IDENTITY primary key NOT NULL,
--    "FirstName" character varying(50) NOT NULL,
--    "LastName" character varying(50) NOT NULL,
--    "Age" smallint NOT NULL,
--    "ContactAdd" character varying(50) NOT NULL,
--    "CustEmail" character varying(50) NOT NULL,
--    "CustPass" character varying(50) NOT NULL,
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAt" timestamp with time zone DEFAULT now()
--);

--CREATE TABLE IF NOT EXISTS public."Pharmacist"
--(
--    "PharId" bigint GENERATED ALWAYS AS IDENTITY primary key NOT NULL,
--    "FirstName" character varying(50) NOT NULL,
--    "LastName" character varying(50) NOT NULL,
--    "Age" smallint NOT NULL,
--    "ContactAdd" character varying(50) NOT NULL,
--    "PharEmail" character varying(50) NOT NULL,
--    "PharPass" character varying(50) NOT NULL,
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAt" timestamp with time zone DEFAULT now()
--);

--CREATE TABLE IF NOT EXISTS public."Medicines"
--(
--    "MedId" bigint GENERATED ALWAYS AS IDENTITY primary key NOT NULL,
--    "MedCategory" character varying(50) NOT NULL,
--    "Name" character varying(50) NOT NULL,
--    "Description" character varying(50) NOT NULL,
--    "Price" character varying(50),
--    "CreatedTime" timestamp with time zone DEFAULT now(),
--    "EndTime" timestamp with time zone DEFAULT now(),
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAt" timestamp with time zone DEFAULT now()
--);

--CREATE TABLE IF NOT EXISTS public."Purchasing"
--(
--    "PurchaseId" bigint GENERATED ALWAYS AS IDENTITY primary key NOT NULL,
--    "CustId" bigint NOT NULL,
--    "MedId" bigint,
--    "Amount" integer NOT NULL,
--    "Date" date DEFAULT now(),
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAd" timestamp with time zone DEFAULT now()
--);

--CREATE TABLE IF NOT EXISTS public."Sales"
--(
--    "SalesId" bigint GENERATED ALWAYS AS IDENTITY primary key NOT NULL,
--    "PharId" bigint,
--    "CustId" bigint,
--    "MedId" bigint,
--    "PurchaseId" bigint,
--    "Count" smallint NOT NULL,
--    "Date" date DEFAULT now(),
--    "TotalAmount" character varying NOT NULL,
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAt" timestamp with time zone DEFAULT now()
--);

--CREATE TABLE IF NOT EXISTS public."Reports"
--(
--    "ReportId" bigint GENERATED ALWAYS AS IDENTITY primary key not null,
--    "PurchaseId" bigint,
--    "SalesId" bigint,
--    "CustId" bigint,
--    "Date" date DEFAULT now(),
--    "CreatedAt" timestamp with time zone DEFAULT now(),
--    "UpdatedAt" timestamp with time zone DEFAULT now()
--);

--ALTER TABLE IF EXISTS public."Purchasing"
--    ADD FOREIGN KEY ("CustId")
--    REFERENCES public."Customer" ("CustID") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Purchasing"
--    ADD FOREIGN KEY ("MedId")
--    REFERENCES public."Medicines" ("MedId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Sales"
--    ADD FOREIGN KEY ("SalesId")
--    REFERENCES public."Sales" ("SalesId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Sales"
--    ADD FOREIGN KEY ("PharId")
--    REFERENCES public."Pharmacist" ("PharId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Sales"
--    ADD FOREIGN KEY ("CustId")
--    REFERENCES public."Customer" ("CustID") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Sales"
--    ADD FOREIGN KEY ("MedId")
--    REFERENCES public."Medicines" ("MedId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Sales"
--    ADD FOREIGN KEY ("PurchaseId")
--    REFERENCES public."Purchasing" ("PurchaseId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Reports"
--    ADD FOREIGN KEY ("PurchaseId")
--    REFERENCES public."Purchasing" ("PurchaseId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Reports"
--    ADD FOREIGN KEY ("SalesId")
--    REFERENCES public."Sales" ("SalesId") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;


--ALTER TABLE IF EXISTS public."Reports"
--    ADD FOREIGN KEY ("CustId")
--    REFERENCES public."Customer" ("CustID") MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE NO ACTION
--    NOT VALID;

--END;